nome = str(input("Digite seu nome completo: ")).strip()
print(f'Seu nome maiúsculo é {nome.upper()}')
print(f'Seu nome minúsculo é {nome.lower()}')
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
